### ISSUE TITLE
How to cross compile for darwin arm64 (ie. Apple Silicon)

### ISSUE THREAD

**Issue by tiero** [plentico/osxcross-target#3]
Looking to use this in a goreleaser pipeline where I want to target also darwin arm64

**Comment by tiero** [comment]
Just answering to myself :) the darwin arm64 targets are there already, I only had to split in a specific build step in goreleaser


Example: 

```yml
 - id: "my-build"
    main: ./cmd/main.go
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=1
      - CC=/home/runner/work/osxcross/target/bin/oa64-clang
      - CXX=/home/runner/work/osxcross/target/bin/oa64-clang++
    goos:
      - darwin
    goarch:
      - arm64
    binary: my-build
```
